using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using StudySync.Models;
using StudySync.Services.Interfaces;

namespace StudySync.ViewModels;

public partial class TodoViewModel : BaseViewModel
{
    private readonly Data.DatabaseService _db;
    private readonly IAuthService _authService;

    [ObservableProperty] private string _newTodoTitle = string.Empty;
    [ObservableProperty] private double _completionProgress;
    [ObservableProperty] private string _progressText = "0 / 0 Completed";

    public ObservableCollection<TodoItem> TodoItems { get; } = new();

    public TodoViewModel(Data.DatabaseService db, IAuthService authService)
    {
        _db = db;
        _authService = authService;
        Title = "Daily To-Do List";
    }

    public async Task LoadTodosAsync()
    {
        IsBusy = true;
        TodoItems.Clear();
        var userId = _authService.CurrentUserId;
        var today = DateTime.Now.Date;

        // Auto-generate today's todos if not already present
        var existing = await _db.GetTodoItemsAsync(userId, today);
        if (existing.Count == 0)
        {
            await GenerateDefaultTodosAsync(userId, today);
            existing = await _db.GetTodoItemsAsync(userId, today);
        }

        foreach (var item in existing)
        {
            TodoItems.Add(item);
        }

        UpdateProgress();
        IsBusy = false;
    }

    private async Task GenerateDefaultTodosAsync(int userId, DateTime today)
    {
        int order = 0;

        // Today's lectures
        var studyDay = (StudyDay)((int)today.DayOfWeek == 0 ? 6 : (int)today.DayOfWeek - 1);
        var lectures = await _db.GetTimetableForDayAsync(userId, studyDay);
        var courses = (await _db.GetCoursesAsync(userId)).ToDictionary(c => c.Id, c => c);

        foreach (var l in lectures)
        {
            var cName = courses.TryGetValue(l.CourseId, out var c) ? c.CourseCode : "Lecture";
            await _db.SaveAsync(new TodoItem
            {
                UserId = userId,
                Title = $"Attend {cName} lecture ({l.StartTime:hh\\:mm})",
                Date = today,
                Order = order++,
                IsAutoGenerated = true,
                RelatedEntityType = RelatedEntityType.Lecture,
                RelatedEntityId = l.Id
            });
        }

        // Today's study sessions
        var sessions = await _db.GetStudySessionsAsync(userId, today);
        foreach (var s in sessions.Where(s => !s.IsBreak))
        {
            await _db.SaveAsync(new TodoItem
            {
                UserId = userId,
                Title = $"Study: {s.Title} ({s.StartTime:hh\\:mm})",
                Date = today,
                Order = order++,
                IsAutoGenerated = true,
                RelatedEntityType = RelatedEntityType.StudySession,
                RelatedEntityId = s.Id
            });
        }
    }

    [RelayCommand]
    private async Task AddTodoAsync()
    {
        if (string.IsNullOrWhiteSpace(NewTodoTitle)) return;

        var userId = _authService.CurrentUserId;
        var item = new TodoItem
        {
            UserId = userId,
            Title = NewTodoTitle.Trim(),
            Date = DateTime.Now.Date,
            Order = TodoItems.Count,
            IsAutoGenerated = false
        };

        await _db.SaveAsync(item);
        TodoItems.Add(item);
        NewTodoTitle = string.Empty;
        UpdateProgress();
    }

    [RelayCommand]
    private async Task ToggleCompleteAsync(TodoItem item)
    {
        if (item is null) return;
        item.IsCompleted = !item.IsCompleted;
        await _db.SaveAsync(item);
        UpdateProgress();
    }

    [RelayCommand]
    private async Task DeleteTodoAsync(TodoItem item)
    {
        if (item is null) return;
        await _db.DeleteAsync(item);
        TodoItems.Remove(item);
        UpdateProgress();
    }

    private void UpdateProgress()
    {
        if (TodoItems.Count == 0)
        {
            CompletionProgress = 0;
            ProgressText = "0 / 0 Completed";
            return;
        }

        var completed = TodoItems.Count(t => t.IsCompleted);
        CompletionProgress = (double)completed / TodoItems.Count;
        ProgressText = $"{completed} / {TodoItems.Count} Completed";
    }
}
