using SQLite;

namespace StudySync.Models;

/// <summary>
/// Represents a to-do item for the daily task list.
/// </summary>
[Table("TodoItems")]
public class TodoItem
{
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }

    [Indexed]
    public int UserId { get; set; }

    [MaxLength(200), NotNull]
    public string Title { get; set; } = string.Empty;

    [MaxLength(500)]
    public string Description { get; set; } = string.Empty;

    public DateTime Date { get; set; }

    public bool IsCompleted { get; set; }

    /// <summary>
    /// Display order for manual reordering.
    /// </summary>
    public int Order { get; set; }

    /// <summary>
    /// Type of related entity (assignment, exam, lecture, etc.).
    /// </summary>
    public RelatedEntityType RelatedEntityType { get; set; } = RelatedEntityType.None;

    /// <summary>
    /// ID of the related entity.
    /// </summary>
    public int? RelatedEntityId { get; set; }

    /// <summary>
    /// Whether this was auto-generated from schedule data.
    /// </summary>
    public bool IsAutoGenerated { get; set; }
}
